let duty={
    dutytitle:{
        type:String,
        required:true
    },
    dutybase:{
        type:String,
        required:true
    },
    dutylocation:{
        type:String,
        required:true
    },
    dutypersonnel:[
       {
           name:{
               type:String,
               require:true
           },
           user:{
               type:string,
               required:true
           },
          from:{
              type:Date,
              required:true
          },
          to:{
              type:Date,
              required:false
          },
          avatar:{
              type:String,
              required:true
          }
       }
    ]
    
}